### ISSUE TITLE
作者能发一下MUIP的项目地址么

### ISSUE THREAD

**Issue by AUndead** [Zhaokugua/Grasscutter-CDKeySystem#1]
作者能发一下MUIP的项目地址么

**Comment by AUndead** [comment]
EMMMM 没事了

**Comment by Zhaokugua** [comment]
MUIP是那个端自带的，如果要找YSGM的话那个原仓库被DMCA了，还有个备份[https://github.com/360NENZ/Crepe-Inc-YSGM](https://github.com/360NENZ/Crepe-Inc-YSGM)
