### ISSUE TITLE
我该如何更改每日签到的奖励？

### ISSUE THREAD

**Issue by AUndead** [Zhaokugua/Grasscutter-CDKeySystem#2]
我该如何更改每日签到的奖励

**Comment by AUndead** [comment]
已解决

**Comment by Zhaokugua** [comment]
每日签到我感觉很灵活，可以是固定奖励也可以是随机奖励之类的，就没想好怎么写
现在里面默认的也是试着做的
如果要改的话，可以修改app/views.py
里面有这几行：
```python
        # 可以用exec_command执行一个命令来获取签到奖励，用户离线时可以用邮件命令发送奖励
        # 然后context的message显示签到结果返回到页面上显示
        # 然后写到数据库记录一下今天已签到
        flag, res = exec_command('/give 202 x1000', uuid)   # give命令需要玩家在线
```
修改一下exec_command里面引号引起来的命令就可以了

**Comment by AUndead** [comment]
> 每日签到我感觉很灵活，可以是固定奖励也可以是随机奖励之类的，就没想好怎么写 现在里面默认的也是试着做的 如果要改的话，可以修改app/views.py 里面有这几行：
> 
> ```python
>         # 可以用exec_command执行一个命令来获取签到奖励，用户离线时可以用邮件命令发送奖励
>         # 然后context的message显示签到结果返回到页面上显示
>         # 然后写到数据库记录一下今天已签到
>         flag, res = exec_command('/give 202 x1000', uuid)   # give命令需要玩家在线
> ```
> 
> 修改一下exec_command里面引号引起来的命令就可以了



 flag, res = exec_command('/give 202 x1000', uuid)   # give命令需要玩家在线
 flag, res = exec_command('/give 101 x1000', uuid)   # give命令需要玩家在线
能不能再复制一个执行多条指令呢

**Comment by Zhaokugua** [comment]
> > 每日签到我感觉很灵活，可以是固定奖励也可以是随机奖励之类的，就没想好怎么写 现在里面默认的也是试着做的 如果要改的话，可以修改app/views.py 里面有这几行：
> > ```python
> >         # 可以用exec_command执行一个命令来获取签到奖励，用户离线时可以用邮件命令发送奖励
> >         # 然后context的message显示签到结果返回到页面上显示
> >         # 然后写到数据库记录一下今天已签到
> >         flag, res = exec_command('/give 202 x1000', uuid)   # give命令需要玩家在线
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 修改一下exec_command里面引号引起来的命令就可以了
> 
> flag, res = exec_command('/give 202 x1000', uuid) # give命令需要玩家在线 flag, res = exec_command('/give 101 x1000', uuid) # give命令需要玩家在线 能不能再复制一个执行多条指令呢

可以是可以，但是后面的代码用来检查执行的命令是否有错误的时候就只会根据最后一条命令的执行正确与否来判断了，可能会出现一些逻辑错误（不过一般也没啥问题）

**Comment by AUndead** [comment]
> > > 每日签到我感觉很灵活，可以是固定奖励也可以是随机奖励之类的，就没想好怎么写 现在里面默认的也是试着做的 如果要改的话，可以修改app/views.py 里面有这几行：
> > > ```python
> > >         # 可以用exec_command执行一个命令来获取签到奖励，用户离线时可以用邮件命令发送奖励
> > >         # 然后context的message显示签到结果返回到页面上显示
> > >         # 然后写到数据库记录一下今天已签到
> > >         flag, res = exec_command('/give 202 x1000', uuid)   # give命令需要玩家在线
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 修改一下exec_command里面引号引起来的命令就可以了
> > 
> > 
> > flag, res = exec_command('/give 202 x1000', uuid) # give命令需要玩家在线 flag, res = exec_command('/give 101 x1000', uuid) # give命令需要玩家在线 能不能再复制一个执行多条指令呢
> 
> 可以是可以，但是后面的代码用来检查执行的命令是否有错误的时候就只会根据最后一条命令的执行正确与否来判断了，可能会出现一些逻辑错误（不过一般也没啥问题）

后台提示:
YSGM命令执行失败！
网站提示：执行兑换时出现异常！请联系管理员！ {'msg': 'give 224 x100', 'retmsg': "can't find gm command:GIVE"}
`        # 可以用exec_command执行一个命令来获取签到奖励，用户离线时可以用邮件命令发送奖励
        # 然后context的message显示签到结果返回到页面上显示
        # 然后写到数据库记录一下今天已签到
        flag, res = exec_command('/give 223 x100', uuid)   # give命令需要玩家在线
        flag, res = exec_command('/give 224 x100', uuid)   # give命令需要玩家在线
        if not flag:
            context = {
                'message': f"执行兑换时出现异常！请联系管理员！	{str(res['data'])}",
                'online_num': online_num,
            }
            return render(request, '每日签到.html', context=context)
        # 成功了就更新一下表，表示今天签到了`

**Comment by Zhaokugua** [comment]
give命令是割草机（grasscutter）用的，
看样子你用的是MUIP的，应该是item add 命令。
可以参考
[https://cmd.d2n.moe/new/](https://cmd.d2n.moe/new/)
[https://gm.casks.me/gm/index.html](https://gm.casks.me/gm/index.html)
这两个命令在线生成工具

**Comment by AUndead** [comment]
> give命令是割草机（grasscutter）用的， 看样子你用的是MUIP的，应该是item add 命令。 可以参考 https://cmd.d2n.moe/new/ https://gm.casks.me/gm/index.html 这两个命令在线生成工具

好的，谢谢！！
