### ISSUE TITLE
[建议]建议在CDK创建功能上加一个多条指令延迟执行功能

### ISSUE THREAD

**Issue by AUndead** [Zhaokugua/Grasscutter-CDKeySystem#4]
在给玩家创建CDK发放衣服的时候给予语句视乎执行太快服务器没有给玩家发放衣服
比如说指令一起执行
/item add 340000
/item add 340001
/item add 340002
/item add 340003
/item add 340004
/item add 340005
 游戏内并不能收到给予的衣服
如果能在指令执行后边加上执行下一条指令的延迟几秒的话就更方便啦！
谢谢作者！

**Comment by Zhaokugua** [comment]
居然有这种问题吗
我之前写的时候还嫌弃他执行命令不够快呢
不过我之前在游戏里手动给衣服好像有时候也收不到，不知道为什么qwq
有空看看

**Comment by Zhaokugua** [comment]
已增加sleep指令可以在执行多条命令时自定义时延。
比如
/give 201 x100
sleep100
/give 201 x100
即可在两条指令执行中间插入一个100ms的时延。
